cmake_minimum_required(VERSION 3.24)

include("${CMAKE_CURRENT_LIST_DIR}/ObsHelpers.cmake")

alpha_recorder_require(REPO_ROOT)
alpha_recorder_require(BUILD_DIR)

set(OBS_ROOT "$ENV{OBS_ROOT}" CACHE PATH "OBS runtime root")
set(STAGE_DIR "${REPO_ROOT}/out/stage/obs" CACHE PATH "Portable OBS stage directory")
set(CONFIGURATION "RelWithDebInfo" CACHE STRING "Build configuration")
set(PLUGIN_NAME "alpha_recorder" CACHE STRING "Main plugin output name")
set(SKIP_PLUGIN_OVERLAY OFF CACHE BOOL "Skip copying Alpha Recorder plugins into the staged OBS plugin directory")
set(CONFIG_FILE "${REPO_ROOT}/deps/obs/obs-root.cmake" CACHE FILEPATH "Generated OBS root CMake fragment")

alpha_recorder_abs_path(REPO_ROOT "${REPO_ROOT}" "${CMAKE_CURRENT_LIST_DIR}")
alpha_recorder_abs_path(BUILD_DIR "${BUILD_DIR}" "${REPO_ROOT}")
alpha_recorder_abs_path(STAGE_DIR "${STAGE_DIR}" "${REPO_ROOT}")
alpha_recorder_abs_path(CONFIG_FILE "${CONFIG_FILE}" "${REPO_ROOT}")

if(CONFIGURATION STREQUAL "")
    set(CONFIGURATION "RelWithDebInfo")
endif()

if(OBS_ROOT STREQUAL "" AND EXISTS "${CONFIG_FILE}")
    file(READ "${CONFIG_FILE}" config_text)
    string(REGEX MATCH "set\\([ \t\r\n]*OBS_ROOT[ \t\r\n]+\"([^\"]+)\"" _match "${config_text}")
    if(CMAKE_MATCH_1)
        set(OBS_ROOT "${CMAKE_MATCH_1}")
    endif()
endif()

if(OBS_ROOT STREQUAL "")
    message(FATAL_ERROR "An OBS developer tree is required. Set OBS_ROOT or write deps/obs/obs-root.cmake before staging.")
endif()

alpha_recorder_abs_path(OBS_ROOT "${OBS_ROOT}" "${REPO_ROOT}")
alpha_recorder_resolve_obs_runtime_root(OBS_ROOT "${OBS_ROOT}")
alpha_recorder_validate_obs_runtime("${OBS_ROOT}")

function(alpha_recorder_find_plugin out_var plugin_name)
    set(candidate_roots
        "${BUILD_DIR}/bin/${CONFIGURATION}"
        "${BUILD_DIR}/${CONFIGURATION}"
        "${BUILD_DIR}/bin"
        "${BUILD_DIR}"
    )

    if(APPLE)
        set(extensions ".plugin" ".dylib")
    elseif(WIN32)
        set(extensions ".dll")
    else()
        set(extensions ".so")
    endif()

    foreach(root IN LISTS candidate_roots)
        if(NOT EXISTS "${root}")
            continue()
        endif()
        foreach(ext IN LISTS extensions)
            set(candidate "${root}/${plugin_name}${ext}")
            if(EXISTS "${candidate}")
                cmake_path(ABSOLUTE_PATH candidate NORMALIZE OUTPUT_VARIABLE resolved)
                set(${out_var} "${resolved}" PARENT_SCOPE)
                return()
            endif()
            if(ext STREQUAL ".so")
                set(candidate "${root}/lib${plugin_name}${ext}")
                if(EXISTS "${candidate}")
                    cmake_path(ABSOLUTE_PATH candidate NORMALIZE OUTPUT_VARIABLE resolved)
                    set(${out_var} "${resolved}" PARENT_SCOPE)
                    return()
                endif()
            endif()
        endforeach()
    endforeach()

    set(${out_var} "" PARENT_SCOPE)
endfunction()

if(APPLE)
    set(app_content_dir "${STAGE_DIR}/OBS.app/Contents")
    set(app_plugin_target_dir "${app_content_dir}/PlugIns")
    set(plugin_target_dir "${STAGE_DIR}/PlugIns")
    set(bin_target_dir "${STAGE_DIR}/Frameworks")
    if(EXISTS "${OBS_ROOT}/Frameworks")
        set(obs_bin_source "${OBS_ROOT}/Frameworks")
    else()
        set(obs_bin_source "${OBS_ROOT}/bin")
    endif()
    if(EXISTS "${OBS_ROOT}/PlugIns")
        set(obs_plugin_source "${OBS_ROOT}/PlugIns")
    else()
        set(obs_plugin_source "${OBS_ROOT}/obs-plugins")
    endif()
    if(EXISTS "${OBS_ROOT}/Resources")
        set(obs_data_source "${OBS_ROOT}/Resources")
    else()
        set(obs_data_source "${OBS_ROOT}/data")
    endif()
    set(portable_plugin_target_dir "${STAGE_DIR}/obs-plugins")
    set(portable_bin_target_dir "${STAGE_DIR}/bin")
    set(portable_data_target_dir "${STAGE_DIR}/data")
elseif(WIN32)
    set(plugin_target_dir "${STAGE_DIR}/obs-plugins/64bit")
    set(bin_target_dir "${STAGE_DIR}/bin/64bit")
    set(obs_bin_source "${OBS_ROOT}/bin/64bit")
    set(obs_plugin_source "${OBS_ROOT}/obs-plugins/64bit")
    set(obs_data_source "${OBS_ROOT}/data")
else()
    alpha_recorder_linux_runtime_layout("${OBS_ROOT}" obs_bin_source obs_plugin_source obs_data_source obs_lib_sources)
    set(bin_target_dir "${STAGE_DIR}/bin")
    if(EXISTS "${OBS_ROOT}/share/obs")
        set(obs_data_source "${OBS_ROOT}/share/obs")
    endif()
    set(data_target_dir "${STAGE_DIR}/share/obs")
    if(obs_plugin_source MATCHES "^${OBS_ROOT}/(.+)$")
        set(plugin_target_dir "${STAGE_DIR}/${CMAKE_MATCH_1}")
    else()
        set(plugin_target_dir "${STAGE_DIR}/lib/obs-plugins")
    endif()
endif()

if(APPLE)
    set(data_target_dir "${STAGE_DIR}/Resources")
elseif(WIN32)
    set(data_target_dir "${STAGE_DIR}/data")
endif()

foreach(required_path IN ITEMS "${obs_bin_source}" "${obs_data_source}" "${obs_plugin_source}")
    if(NOT EXISTS "${required_path}")
        message(FATAL_ERROR "OBS root is missing required path: ${required_path}")
    endif()
endforeach()

if(APPLE)
    file(REMOVE_RECURSE "${STAGE_DIR}/OBS.app")
    file(MAKE_DIRECTORY "${app_content_dir}")
    file(COPY "${OBS_ROOT}/" DESTINATION "${app_content_dir}")
else()
    file(REMOVE_RECURSE "${STAGE_DIR}")
endif()
file(MAKE_DIRECTORY "${plugin_target_dir}" "${bin_target_dir}" "${data_target_dir}")
file(COPY "${obs_bin_source}/" DESTINATION "${bin_target_dir}")
file(COPY "${obs_data_source}/" DESTINATION "${data_target_dir}")
if(UNIX AND NOT APPLE)
    foreach(obs_lib_source IN LISTS obs_lib_sources)
        if(obs_lib_source MATCHES "^${OBS_ROOT}/(.+)$")
            set(obs_lib_target_dir "${STAGE_DIR}/${CMAKE_MATCH_1}")
            file(GLOB obs_lib_entries LIST_DIRECTORIES true "${obs_lib_source}/*")
            foreach(obs_lib_entry IN LISTS obs_lib_entries)
                get_filename_component(obs_lib_entry_name "${obs_lib_entry}" NAME)
                if(obs_lib_entry_name STREQUAL "obs-plugins")
                    continue()
                endif()
                file(COPY "${obs_lib_entry}" DESTINATION "${obs_lib_target_dir}")
            endforeach()
        endif()
    endforeach()
else()
    file(COPY "${obs_plugin_source}/" DESTINATION "${plugin_target_dir}")
endif()
if(APPLE AND EXISTS "${OBS_ROOT}/MacOS")
    file(COPY "${OBS_ROOT}/MacOS/" DESTINATION "${STAGE_DIR}/MacOS")
endif()
if(APPLE)
    file(MAKE_DIRECTORY "${portable_plugin_target_dir}" "${portable_bin_target_dir}" "${portable_data_target_dir}")
    file(COPY "${obs_bin_source}/" DESTINATION "${portable_bin_target_dir}")
    file(COPY "${obs_data_source}/" DESTINATION "${portable_data_target_dir}")
    file(COPY "${obs_plugin_source}/" DESTINATION "${portable_plugin_target_dir}")
endif()

set(main_plugin_path "")
set(frontend_plugin_path "")
set(e2e_plugin_path "")
if(NOT SKIP_PLUGIN_OVERLAY)
    foreach(plugin IN ITEMS "${PLUGIN_NAME}" alpha_recorder_frontend alpha_recorder_e2e)
        alpha_recorder_find_plugin(plugin_path "${plugin}")
        if(plugin STREQUAL "${PLUGIN_NAME}" AND plugin_path STREQUAL "")
            message(FATAL_ERROR "Failed to locate ${PLUGIN_NAME} in the build tree: ${BUILD_DIR}")
        endif()
        if(NOT plugin_path STREQUAL "")
            if(IS_DIRECTORY "${plugin_path}")
                file(COPY "${plugin_path}" DESTINATION "${plugin_target_dir}")
                if(APPLE)
                    file(COPY "${plugin_path}" DESTINATION "${app_plugin_target_dir}")
                    file(COPY "${plugin_path}" DESTINATION "${portable_plugin_target_dir}")
                endif()
            else()
                get_filename_component(plugin_file_name "${plugin_path}" NAME)
                file(COPY_FILE "${plugin_path}" "${plugin_target_dir}/${plugin_file_name}" ONLY_IF_DIFFERENT)
                if(APPLE)
                    file(COPY_FILE "${plugin_path}" "${app_plugin_target_dir}/${plugin_file_name}" ONLY_IF_DIFFERENT)
                    file(COPY_FILE "${plugin_path}" "${portable_plugin_target_dir}/${plugin_file_name}" ONLY_IF_DIFFERENT)
                endif()
            endif()
            if(plugin STREQUAL "${PLUGIN_NAME}")
                set(main_plugin_path "${plugin_path}")
            elseif(plugin STREQUAL "alpha_recorder_frontend")
                set(frontend_plugin_path "${plugin_path}")
            elseif(plugin STREQUAL "alpha_recorder_e2e")
                set(e2e_plugin_path "${plugin_path}")
            endif()
        endif()
    endforeach()
endif()

alpha_recorder_write_json_manifest("${STAGE_DIR}/stage.manifest.json"
    "obsRoot=${OBS_ROOT}"
    "buildDir=${BUILD_DIR}"
    "stageDir=${STAGE_DIR}"
    "configuration=${CONFIGURATION}"
    "pluginPath=${main_plugin_path}"
    "frontendPluginPath=${frontend_plugin_path}"
    "e2ePluginPath=${e2e_plugin_path}"
)

message(STATUS "Staged OBS tree at ${STAGE_DIR}")
